# NetlifyCMS configuration
# see: https://www.netlifycms.org/docs/configuration-options/

backend:
  # Refer to https://www.netlifycms.org/docs/authentication-backends/ for auth backend list and instructions
  name: git-gateway
  accept_roles:
    - admin
    - editor

  # Branch to update
  branch: master

  # Repo for pushing new commits. Make sure this is correct!
  repo: hkennyv/kennyvh.com

# NetlifyCMS will include a link back to the main site
display_url: https://kennyvh.com
site_url: https://kennyvh.com

# fix logo for NetlifyCMS login screen
# logo_url: https://epic-lamport-ce50c0.netlify.com/logos/dl-khuynh.jpg

# Enable draft branches
publish_mode: editorial_workflow

media_folder: public/images/uploads
public_folder: /images/uploads

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", required: false }
      - {
          label: "Short Description",
          name: "description",
          widget: "string",
          required: false,
        }
      - {
          label: "Cover Image",
          name: "cover",
          widget: "image",
          required: false,
        }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
