
# NetlifyCMS configuration
# see: https://www.netlifycms.org/docs/configuration-options/

backend:
  # Refer to https://www.netlifycms.org/docs/authentication-backends/ for auth backend list and instructions
  name: git-gateway
  accept_roles:
    - admin
    - editor

  # Branch to update
  branch: master

  # Repo for pushing new commits. Make sure this is correct!
  repo: hkennyv/kennyvh.com
  
# NetlifyCMS will include a link back to the main site
display_url: https://kennyvh.com/
site_url: https://kennyvh.com/

# fix logo for NetlifyCMS login screen
# logo_url: https://epic-lamport-ce50c0.netlify.com/logos/dl-khuynh.jpg

# Enable draft branches
publish_mode: editorial_workflow

media_folder: public/images/uploads
public_folder: /images/uploads

# https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    description: "All the posts!"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags (comma-delimited)", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }